# ドキュメント整合性チェック設定ファイル

# 除外するディレクトリ
exclude_dirs:
  - .git
  - .mypy_cache
  - .pytest_cache
  - .ruff_cache
  - .venv
  - node_modules
  - __pycache__
  - archive
  - output

# 除外するファイルパターン
exclude_files:
  - "*.tmp"
  - "*.bak"
  - "*~"

# バージョンチェック設定
version_check:
  # 除外するバージョンパターン（正規表現）
  exclude_patterns:
    - '^20\.\d+\.\d+$'    # Docker versions (20.x.x)
    - '^24\.\d+\.\d+$'    # Docker versions (24.x.x)
    - '^2\.\d+\.\d+$'     # Docker Compose versions (2.x.x)
    - '^0\.2\.\d+$'       # uv versions (0.2.x)
    - '^0\.0\.\d+$'       # Development versions
    - '^1\.3\.\d+$'       # GitHub CLI versions
    - '^2\.20\.\d+$'      # Docker Compose specific versions
    - '^2\.40\.\d+$'      # Docker Compose specific versions

  # プロジェクトバージョンのパターン
  project_patterns:
    - 'version["\s]*[:=]["\s]*([0-9]+\.[0-9]+\.[0-9]+)'
    - 'mcp-docker["\s]*[:=]["\s]*v?([0-9]+\.[0-9]+\.[0-9]+)'
    - 'リリース\s*v?([0-9]+\.[0-9]+\.[0-9]+)'

# リンクチェック設定
link_check:
  # 除外するリンクパターン
  exclude_patterns:
    - '^https?://'        # 外部リンク
    - '^mailto:'          # メールリンク
    - '^#'                # アンカーのみ

  # チェックするファイル拡張子
  check_extensions:
    - .md
    - .rst
    - .txt

# 整合性チェック設定
consistency_check:
  # 古い情報のパターン
  outdated_patterns:
    pip_usage:
      pattern: 'pip\s+install'
      message: "pip使用"
      suggestion: "uvを使用してください"
    npm_usage:
      pattern: 'npm\s+install'
      message: "npm使用"
      suggestion: "uvまたは適切なパッケージマネージャーを使用してください"
    python_pip:
      pattern: 'python\s+-m\s+pip'
      message: "pip使用"
      suggestion: "uvを使用してください"
    requirements_txt:
      pattern: 'requirements\.txt'
      message: "requirements.txt"
      suggestion: "pyproject.tomlを使用してください"

  # 矛盾する記述のパターン
  contradiction_patterns:
    docker_desktop_required:
      pattern: 'Docker\s+Desktop.*必須'
      message: "Docker Desktop必須"
      suggestion: "Docker Engineでも動作します"
    root_permission:
      pattern: 'root.*権限.*必要'
      message: "root権限必要"
      suggestion: "rootless Dockerを推奨しています"

# レポート設定
report:
  # 出力形式
  formats:
    - console
    - json

  # 詳細レベル
  detail_levels:
    - summary
    - detailed
    - verbose

  # CI/CD設定
  ci_mode:
    fail_on_critical: true
    fail_on_warnings: false
    output_format: "simple"
