# MegaLinter configuration for the Mcp-Docker project
# https://oxsecurity.github.io/megalinter/latest/configuration

APPLY_FIXES: none
PRINT_ALPACA: false
REPORT_OUTPUT_FOLDER: megalinter-reports
IGNORE_GITIGNORED_FILES: true
DEFAULT_WORKSPACE: .

FILTER_REGEX_EXCLUDE: >-
  (^archive/|
   ^output/|
   ^docs/_build/|
   __pycache__/|
   ^.venv/)

ENABLE_LINTERS:
  - BASH_SHELLCHECK
  - DOCKERFILE_HADOLINT
  - YAML_YAMLLINT
  - PYTHON_RUFF

DISABLE_LINTERS:
  - REPOSITORY_GIT_DIFF  # Dockerコンテナ内ではgitリポジトリが利用できないため無効化

# Linter-specific configuration overrides can be added here as needed
