coverage:
  precision: 2
  round: down
  range: 60..90
  status:
    project:
      default:
        target: auto
        threshold: 2%
    patch:
      default:
        target: 70%
        threshold: 5%

comment:
  layout: reach,diff,flags,files
  behavior: default
  require_changes: false

flags:
  go-cli:
    paths:
      - cmd/
      - internal/
