---
services:
  datetime-validator:
    image: ghcr.io/scottlz0310/mcp-docker:latest
    container_name: mcp-datetime
    env_file: .env
    user: "${USER_ID:-1000}:${GROUP_ID:-1000}"
    volumes:
      - ${WATCH_DIRECTORY:-./docs}:/workspace:ro
      - ./output:/output:rw
    restart: unless-stopped
    command:
      - python
      - services/datetime/datetime_validator.py
      - --directory
      - /workspace
    networks:
      - mcp-network
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: "0.5"
    privileged: false
    cap_drop:
      - ALL

networks:
  mcp-network:
    driver: bridge
