# Prometheus設定ファイル
# GitHub Actions Simulator 監視用設定

global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus自体の監視
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Actions Simulator の監視
  - job_name: 'actions-simulator'
    static_configs:
      - targets: ['actions-server:8000']
    metrics_path: '/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s

  # Docker コンテナの監視（cAdvisor使用時）
  - job_name: 'docker'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 30s

  # Node Exporter（システムメトリクス）
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 30s
