---
services:
  actions-simulator:
    image: ghcr.io/scottlz0310/mcp-docker-actions:latest
    container_name: mcp-actions
    env_file: .env
    volumes:
      - ${PWD}:/workspace:ro
      - /var/run/docker.sock:/var/run/docker.sock
    restart: "no"
    command:
      - "act"
    networks:
      - mcp-network

networks:
  mcp-network:
    driver: bridge
