#!/usr/bin/env bash
# Setup Docker environment variables for Actions Simulator

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"

cd "${PROJECT_ROOT}"

echo "🔧 Docker環境セットアップ"

# Get Docker group ID
DOCKER_GID=$(getent group docker | cut -d: -f3 2>/dev/null || echo "999")

# Get user information
USER_ID=$(id -u)
GROUP_ID=$(id -g)

echo "📋 環境情報:"
echo "   USER_ID=${USER_ID}"
echo "   GROUP_ID=${GROUP_ID}"
echo "   DOCKER_GID=${DOCKER_GID}"

# Export environment variables for current session
export USER_ID="${USER_ID}"
export GROUP_ID="${GROUP_ID}"
export DOCKER_GID="${DOCKER_GID}"

# Create or update .env file
ENV_FILE=".env"
TEMP_ENV_FILE=".env.tmp"

echo "📄 .env ファイル更新中..."

# Start with existing .env if it exists
if [ -f "${ENV_FILE}" ]; then
    # Remove existing Docker-related variables
    grep -v "^USER_ID=" "${ENV_FILE}" | \
    grep -v "^GROUP_ID=" | \
    grep -v "^DOCKER_GID=" | \
    grep -v "^ACT_LOG_LEVEL=" | \
    grep -v "^ACT_PLATFORM=" | \
    grep -v "^ACTIONS_SIMULATOR_VERBOSE=" > "${TEMP_ENV_FILE}" || true
else
    touch "${TEMP_ENV_FILE}"
fi

# Add Docker environment variables
cat >> "${TEMP_ENV_FILE}" << EOF

# =============================================================================
# MCP Docker Environment - 自動生成設定ファイル
# =============================================================================
# このファイルは自動生成されます。手動編集は推奨されません。
#
# GitHub Personal Access Token (GPAT) について:
# 以下の環境変数から自動的に取得されます（優先順位順）:
#   1. GITHUB_PERSONAL_ACCESS_TOKEN
#   2. GITHUB_TOKEN
#   3. GH_TOKEN
#
# 設定方法:
#   export GITHUB_TOKEN="your_token_here"
#   または
#   export GITHUB_PERSONAL_ACCESS_TOKEN="your_token_here"
# =============================================================================

# Docker Environment Variables (Auto-generated by setup-docker-env.sh)
USER_ID=${USER_ID}
GROUP_ID=${GROUP_ID}
DOCKER_GID=${DOCKER_GID}

# Actions Simulator Settings
ACT_LOG_LEVEL=info
ACT_PLATFORM=ubuntu-latest=catthehacker/ubuntu:act-latest
ACTIONS_SIMULATOR_VERBOSE=true
EOF

# Replace the original .env file
mv "${TEMP_ENV_FILE}" "${ENV_FILE}"

echo "✅ .env ファイルを更新しました"

# Test Docker access
echo "🐳 Docker接続テスト..."
if docker version >/dev/null 2>&1; then
    echo "✅ Docker接続OK"
else
    echo "⚠️ Docker接続に問題があります"
    echo "💡 以下のコマンドを実行してください:"
    echo "   sudo usermod -aG docker $USER"
    echo "   newgrp docker"
    echo "   または"
    echo "   sudo chmod 666 /var/run/docker.sock"
fi

# GitHub Personal Access Token の確認
echo "🔑 GitHub Personal Access Token確認..."
if [ -n "${GITHUB_PERSONAL_ACCESS_TOKEN:-}" ]; then
    echo "✅ GITHUB_PERSONAL_ACCESS_TOKEN が設定されています"
elif [ -n "${GITHUB_TOKEN:-}" ]; then
    echo "✅ GITHUB_TOKEN が設定されています"
elif [ -n "${GH_TOKEN:-}" ]; then
    echo "✅ GH_TOKEN が設定されています"
else
    echo "⚠️ GitHub Personal Access Token が設定されていません"
    echo "💡 以下のいずれかの環境変数を設定してください:"
    echo "   export GITHUB_TOKEN=\"your_token_here\""
    echo "   export GITHUB_PERSONAL_ACCESS_TOKEN=\"your_token_here\""
    echo "   export GH_TOKEN=\"your_token_here\""
fi

echo "✅ Docker環境セットアップ完了"
