# ドキュメント整合性チェック GitHub Actions ワークフロー
name: Documentation Consistency Check

on:
  push:
    branches: [main, develop]
    paths:
      - '**.md'
      - 'docs/**'
      - 'pyproject.toml'
  pull_request:
    branches: [main]
    paths:
      - '**.md'
      - 'docs/**'
      - 'pyproject.toml'

jobs:
  docs-check:
    name: Check Documentation Consistency
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          version: "latest"

      - name: Install dependencies
        run: |
          uv sync --group dev

      - name: Run documentation consistency check
        run: |
          uv run python scripts/check-docs-consistency.py \
            --ci-mode \
            --fail-on-issues \
            --output docs-consistency-report.json

      - name: Upload documentation report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: docs-consistency-report
          path: docs-consistency-report.json
