---
name: Simple Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Simple test
        run: |
          echo "Hello, World!"
          echo "Current directory: $(pwd)"
          echo "Files: $(ls -la)"
