---
name: Test CI Workflow

"on":
  push:
    branches: [main, feature/*]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || echo "No requirements.txt found"

      - name: Run basic tests
        run: |
          echo "Running basic tests..."
          python --version
          ls -la

      - name: Show environment
        run: |
          echo "GitHub Workspace: $GITHUB_WORKSPACE"
          echo "GitHub Repository: $GITHUB_REPOSITORY"
          echo "Current directory: $(pwd)"

  lint:
    name: Code Linting
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run linter
        run: |
          echo "Running linter checks..."
          echo "✓ All lint checks passed"

  build:
    name: Build Application
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build application
        run: |
          echo "Building application..."
          echo "✓ Build completed successfully"
