name: test-env
on:
  workflow_dispatch:
jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - name: Print Token
        run: |
          echo "TOKEN=$ACTIONS_RUNTIME_TOKEN"
          if [ -z "$ACTIONS_RUNTIME_TOKEN" ]; then
            echo "TOKEN is empty" && exit 1
          fi
